Universe           = vanilla
Executable         = plot_mass.sh
Output          = /sphenix/tg/tg01/hf/gregoryottino/lightFlavorMultRatio/kfp_production_sim/mass_histogram_output/logs/massplot_$(Process).out
Error           = /sphenix/tg/tg01/hf/gregoryottino/lightFlavorMultRatio/kfp_production_sim/mass_histogram_output/logs/massplot_$(Process).err
Log             = /tmp/log_gregoryottino/massplot_$(Process).log
Initialdir      = /sphenix/tg/tg01/hf/gregoryottino/lightFlavorMultRatio/analysis/LightFlavorRatios/mass_histograms/
PeriodicHold    = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 2GB
Priority           = 20
job_lease_duration = 3600
Arguments          = $INT(Process,%06d)
Queue 10000
